name: Monitor GBP Docs

on:
  schedule:
    - cron: '0 7 * * *'        # zilnic la 07:00 UTC
  workflow_dispatch:            # buton „Run workflow”

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --quiet requests beautifulsoup4 slack_sdk

      - name: Run changelog monitor
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        run: python scripts/check_gbp_updates.py
